# global context
[build]
command = "gulp build"
publish = "public"
# build a preview (optional)
[context.deploy-preview]
command = "gulp build-preview"
# build a branch with debug (optional)
[context.branch-deploy]
command = "gulp build-debug"
# Below reference: https://answers.netlify.com/t/access-control-allow-origin-policy/1813/40
[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
